# Generated by Django 5.2.16 on 2026-07-25 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('semester', models.CharField(help_text='e.g. 2025/2026 Semester 1', max_length=30)),
                ('ca_total_weight', models.PositiveIntegerField(blank=True, help_text='Expected total CA marks (e.g. 30 or 40). Used only as a sanity-check warning when scores are uploaded — not enforced.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('code', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('assessment_columns', models.JSONField(help_text='Ordered list of [name, max_score] pairs used in this upload.')),
                ('is_active', models.BooleanField(default=True)),
                ('accepted_row_count', models.PositiveIntegerField(default=0)),
                ('rejected_row_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Registration number must be in the format PS/CSC/22/0001.', regex='^[A-Z]{2,4}/[A-Z]{2,5}/\\d{2}/\\d{4}$')])),
                ('name', models.CharField(max_length=150)),
                ('scores', models.JSONField(help_text='{column_name: score_or_null}')),
                ('raw_total_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('raw_max_total', models.DecimalField(decimal_places=2, help_text='Sum of max scores for columns that were actually graded this upload.', max_digits=7)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low_fill_warning', models.BooleanField(default=False, help_text='Fewer than 3 (or fewer than the number of active columns, whichever is smaller) assessment columns had a score for this student.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.course')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.uploadbatch')),
            ],
            options={
                'ordering': ['reg_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Registration number must be in the format PS/CSC/22/0001.', regex='^[A-Z]{2,4}/[A-Z]{2,5}/\\d{2}/\\d{4}$')])),
                ('name', models.CharField(max_length=150)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='courses.course')),
            ],
            options={
                'ordering': ['reg_number'],
                'unique_together': {('course', 'reg_number')},
            },
        ),
    ]
